---
# tasks file for ansible-vector
- name: Vector | install
  ansible.builtin.include_tasks: "{{ ansible_pkg_mgr }}/install.yml"

- name: Vector | create service
  ansible.builtin.template:
    src: vector.service.j2
    dest: /etc/systemd/system/vector.service
    mode: "0644"
    owner: "root"
    group: "root"
  notify: (Handler) Run Vector
