---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos-stream-8
    image: quay.io/centos/centos:stream8
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: "/sbin/init"
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    verify: verify.yml
